name: Elixir CI

on:
  push:
  pull_request:
    
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-22.04
    env:
      MIX_ENV: test
      CHECK_FORMAT: true
      elixir_version: "1.14.5"
      otp_version: "25.3.2"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.15
        with:
          otp-version: ${{env.otp_version}}
          elixir-version: ${{env.elixir_version}}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
      - name: Get deps
        run: mix deps.get
      - name: Compile
        run: mix compile --warnings-as-errors
      - name: Run tests
        run: mix test
  mix-format:
    name: Mix-Format and Credo tests
    runs-on: ubuntu-22.04
    env:
      elixir_version: "1.14.5"
      otp_version: "25.3.2"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.15
        with:
          otp-version: ${{env.otp_version}}
          elixir-version: ${{env.elixir_version}}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
      - name: Install dependencies
        run: mix deps.get
      - name: Run format check
        run: mix format --check-formatted
      - name: Credo checks
        run: mix credo --strict
      - name: Dialyzer checks
        run: mix dialyze
      - name: Run docs
        run: mix docs
